[Dojot-module-nodejs] Remove travis and make changes to use github actions
dojot/dojot-module-nodejs pull request #79
Opened 2021-04-23 13:51 UTC by marianoleonardo

dojot/dojot#1913

2021-04-23 13:53 UTC, mprevide requested changes
There are 2 points
 - documentation
 - auto publish in npm

2021-04-26 12:59 UTC, mprevide commented
Can you publish in your npm account?

2021-04-26 19:44 UTC, mprevide approved these changes
Don't worry about DeepScan error

2021-04-27 16:55 UTC, thiagodpf commented on .github/workflows/main.yml
> +        node-version: [8.x]
This module is now available for Node.js v12.x

2021-04-27 16:59 UTC, thiagodpf commented on .github/workflows/publish-npm-packages.yml
> +            node-version: '10.x'
you may also have to switch to version `12.x` here...

2021-04-27 17:00 UTC, thiagodpf commented on .github/workflows/publish-npm-packages.yml
> +            node-version: '10.x'
```waml
with:
          node-version: ${{ matrix.node-version }}
```

2021-04-27 17:13 UTC, mprevide commented on .github/workflows/publish-npm-packages.yml
> +            node-version: '10.x'
yes, but almost all services that use it are in node 8 or 10

2021-04-27 17:13 UTC, mprevide commented on .github/workflows/main.yml
> +        node-version: [8.x]
yes, but almost all services that use it are in node 8 or 10

2021-04-27 17:14 UTC, mprevide commented on .github/workflows/main.yml
> +        node-version: [8.x]
maybe just here you must change to `[8.x, 10.x, 12.x]`

2021-04-27 18:43 UTC, thiagodpf approved these changes

2021-04-27 19:01 UTC, mprevide commented on .github/workflows/main.yml
> +        node-version: [8.x]
Maybe you can change to 10.x

2021-04-28 13:26 UTC, mprevide approved these changes

2021-04-28 22:24 UTC, mprevide requested changes
Remove badge travis from readme

2021-04-29 14:00 UTC, mprevide approved these changes

2021-04-29 14:20 UTC, merged